[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "ethereum-testing-tools"
version = "0.1.0"
description = "Utilities and scripts for testing Ethereum-based blockchains."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "web3==7.8.0",
    "eth-utils==5.0.0",
    "ckzg==2.0.1",
    "requests==2.31.0",
    "grafana-client==4.3.1",
    "pyyaml",
    "pandas",
]

[project.scripts]
generate-account = "scripts.generate_account:main"

[tool.setuptools]
packages = ["scripts"]
